name: "Build Armbian"
on:
  workflow_dispatch:
jobs:
  build-armbian:
    runs-on: ubuntu-latest
    steps:
      - uses: armbian/build@v24.11.0-trunk.368
        with:
          armbian_token:     "${{ secrets.GITHUB_TOKEN }}"  # GitHub token
          armbian_release:   "bookworm"                        # userspace
          armbian_kernel_branch:  "edge"
          armbian_target:    "build"                        # build=image, kernel=kernel
          armbian_board:     "orangepiprime"                   # build target
          armbian_ui:  "server"
          
