
name: "Test2 Build Armbian"
on:
  workflow_dispatch:
jobs:
  build-armbian:
    runs-on: ubuntu-latest
    steps:
      - run: "git clone https://github.com/armbian/build && cd build && git switch -c v25.2.0-trunk.3 && ./compile.sh BOARD=orangepiprime BRANCH=edge RELEASE=bookworm BUILD_MINIMAL=no BUILD_DESKTOP=no KERNEL_CONFIGURE=no"
  release:
    needs: build-armbian
    runs-on: ubuntu-latest
    steps:
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v4
      with:
        name: Armbian-unofficial_Orangepiprime_bookworm_edge.img
        path: ./build/output/images/*.img
        
        
